<?php

namespace PartnershipBundle\Repository;

/**
 * CategoriePartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriePartenaireRepository extends \Doctrine\ORM\EntityRepository
{
}
