event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /

partnership:
    resource: "@PartnershipBundle/Controller/"
    type:     annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"