<?php

namespace EventBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                FROM EventBundle:Evenement e
                WHERE e.nomEvenement LIKE :str'
            )
            ->setParameter('str', '%' . $str . '%')
            ->getResult();
    }


}
